version: '2'

services:
  # PostgreSQL database
  db:
    image: postgres:9.6
    hostname: db
    container_name: extension_db
    env_file: .env
    volumes:
      - "pgdata:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  # RabbitMQ
  rabbit:
    hostname: rabbit
    container_name: extension_rabbit
    image: rabbitmq:3.7.3-management
    env_file: .env
    expose:
      - "5672"
    ports:
#      - "5673:5672"  # we forward this port because it's useful for debugging
      - "15673:15672"  # here, we can access rabbitmq management plugin

  # Celery worker
  celery:
    build:
      context: .
      dockerfile: DockerfileCelery
    command: ./run_celery.sh
    container_name: extension_celery
    env_file: .env
    environment:
      - DEBUG=false
    volumes:
      - .:/app
    links:
      - db
      - rabbit

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery_beat.sh
    container_name: extension_celery_beat
    env_file: .env
    environment:
      - DEBUG=0
    volumes:
      - .:/app
    links:
      - db
      - rabbit

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: "flower -A extension.celery_app --conf=extension/flowerconfig.py --port=5555"
    container_name: extension_flower
    ports:
      - "5556:5555"
    env_file:
      - .env
    links:
      - celery
      - rabbit

  # Django web server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extension_backend
    hostname: backend
    env_file: .env
    command: ./run_server.sh
    volumes:
      - .:/app  # mount current directory inside container
    ports:
      - "8000:8000"
    # set up links so that web knows about db, rabbit
    links:
      - db
      - rabbit
    depends_on:
      - db

  # Frontend container (static React files, index.html and bundle.js, served with nginx)
#  frontend:
#    build: ../subtitles-frontend
#    volumes:
#      - ../subtitles-frontend:/app/frontend
#    container_name: extension_frontend
#    hostname: frontend
##    working_dir: /app/frontend
#    links:
#      - backend

  nginx_proxy:
    build: ./configs/nginx
    container_name: extension_nginx
    # See the file nginx_proxy.conf
    # It uses these links to connect you to the two containers
    links:
      - backend
#      - frontend
    ports:
      - '81:80'

volumes:
  pgdata:

networks:
  default: